/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import db.Cheque;
import db.DBManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Edgardo Rivero
 */
public class GenerarCheque extends javax.swing.JFrame {
    DBManager dbManager = new DBManager();
    /**
     * Creates new form IngresarUsuario
     */
    public GenerarCheque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        jLabelCuentaBancaria = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jLabelConcepto = new javax.swing.JLabel();
        jLabelProveedor = new javax.swing.JLabel();
        jLabelImporte = new javax.swing.JLabel();
        jLabelEstatus = new javax.swing.JLabel();
        jLabelTipoOperacion = new javax.swing.JLabel();
        textFieldFecha = new javax.swing.JTextField();
        textFieldNumero = new javax.swing.JTextField();
        textFieldConcepto = new javax.swing.JTextField();
        textFieldProveedor = new javax.swing.JTextField();
        textFieldImporte = new javax.swing.JTextField();
        jComboBoxElegirCuenta = new javax.swing.JComboBox<>();
        jComboBoxEstatus = new javax.swing.JComboBox<>();
        jComboBoxTipoOperacion = new javax.swing.JComboBox<>();
        jButtonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setToolTipText("");
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(204, 204, 204));
        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Nuevo Cheque");
        Titulo.setToolTipText("");
        Titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Titulo.setOpaque(true);
        background.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 480, 40));

        jLabelCuentaBancaria.setBackground(new java.awt.Color(0, 51, 255));
        jLabelCuentaBancaria.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabelCuentaBancaria.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCuentaBancaria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCuentaBancaria.setText("Cuenta Bancaria");
        jLabelCuentaBancaria.setToolTipText("");
        jLabelCuentaBancaria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelCuentaBancaria.setOpaque(true);
        background.add(jLabelCuentaBancaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 200, 30));

        jLabelFecha.setBackground(new java.awt.Color(0, 51, 255));
        jLabelFecha.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFecha.setText("Fecha");
        jLabelFecha.setToolTipText("");
        jLabelFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelFecha.setOpaque(true);
        background.add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 200, 30));

        jLabelNumero.setBackground(new java.awt.Color(0, 51, 255));
        jLabelNumero.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabelNumero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumero.setText("Numero");
        jLabelNumero.setToolTipText("");
        jLabelNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelNumero.setOpaque(true);
        background.add(jLabelNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 200, 30));

        jLabelConcepto.setBackground(new java.awt.Color(0, 51, 255));
        jLabelConcepto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabelConcepto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConcepto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConcepto.setText("Concepto");
        jLabelConcepto.setToolTipText("");
        jLabelConcepto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelConcepto.setOpaque(true);
        background.add(jLabelConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 200, 30));

        jLabelProveedor.setBackground(new java.awt.Color(0, 51, 255));
        jLabelProveedor.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabelProveedor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProveedor.setText("Proveedor");
        jLabelProveedor.setToolTipText("");
        jLabelProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelProveedor.setOpaque(true);
        background.add(jLabelProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 200, 30));

        jLabelImporte.setBackground(new java.awt.Color(0, 51, 255));
        jLabelImporte.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabelImporte.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImporte.setText("Importe");
        jLabelImporte.setToolTipText("");
        jLabelImporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelImporte.setOpaque(true);
        background.add(jLabelImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 200, 30));

        jLabelEstatus.setBackground(new java.awt.Color(0, 51, 255));
        jLabelEstatus.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabelEstatus.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstatus.setText("Estatus");
        jLabelEstatus.setToolTipText("");
        jLabelEstatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelEstatus.setOpaque(true);
        background.add(jLabelEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 200, 30));

        jLabelTipoOperacion.setBackground(new java.awt.Color(0, 51, 255));
        jLabelTipoOperacion.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabelTipoOperacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoOperacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTipoOperacion.setText("Tipo Operacion");
        jLabelTipoOperacion.setToolTipText("");
        jLabelTipoOperacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelTipoOperacion.setOpaque(true);
        background.add(jLabelTipoOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 200, 30));

        textFieldFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFechaActionPerformed(evt);
            }
        });
        background.add(textFieldFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 190, 27));

        textFieldNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNumeroActionPerformed(evt);
            }
        });
        background.add(textFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 190, 27));

        textFieldConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldConceptoActionPerformed(evt);
            }
        });
        background.add(textFieldConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 190, 27));

        textFieldProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldProveedorActionPerformed(evt);
            }
        });
        background.add(textFieldProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 190, 27));

        textFieldImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldImporteActionPerformed(evt);
            }
        });
        background.add(textFieldImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 190, 27));

        jComboBoxElegirCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(dbManager.opcionesComboCuenta()));
        jComboBoxElegirCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxElegirCuentaActionPerformed(evt);
            }
        });
        background.add(jComboBoxElegirCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 190, 30));

        jComboBoxEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(dbManager.opcionesComboEstatus()));
        jComboBoxEstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstatusActionPerformed(evt);
            }
        });
        background.add(jComboBoxEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 190, 30));

        jComboBoxTipoOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(dbManager.opcionesComboTipoOperacion()));
        jComboBoxTipoOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoOperacionActionPerformed(evt);
            }
        });
        background.add(jComboBoxTipoOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 190, 30));

        jButtonAceptar.setText("Generar Cheque");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        background.add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Cheque cheque = new Cheque();
    private void jComboBoxTipoOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoOperacionActionPerformed
        
    }

    private void textFieldFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldFechaActionPerformed
        String fecha = textFieldFecha.getText();
        if (fecha.matches("\\d{4}-\\d{2}-\\d{2}")) {
            cheque.setFecha(java.sql.Date.valueOf(fecha));
        } else {
            JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto. El formato correcto es yyyy-MM-dd");
        }
    }
    

    private void textFieldNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNumeroActionPerformed
        
    }

    private void textFieldConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldConceptoActionPerformed
        String concepto = textFieldConcepto.getText();
        if (concepto.length() > 0) {
            cheque.setConcepto(concepto);
        } else {
            JOptionPane.showMessageDialog(this, "El campo concepto no puede estar vacío");
        }
    }

    private void textFieldProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldProveedorActionPerformed
        String proveedor = textFieldProveedor.getText();
        int proveedorInt = Integer.parseInt(proveedor);
        if (dbManager.validarProveedorExiste(proveedorInt)) {
            cheque.setMaeProveedor(proveedorInt);
        } else {
            JOptionPane.showMessageDialog(this, "El proveedor no existe");
        }
    }

    private void textFieldImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldImporteActionPerformed
        String importe = textFieldImporte.getText().replace(",", ".");
        if (importe.matches("\\d+(\\.\\d+)?")) {
            cheque.setImporte(new java.math.BigDecimal(importe));
        } else {
            JOptionPane.showMessageDialog(this, "Formato de importe incorrecto. Solo se permiten números enteros y decimales separados por punto");
        }
    }

    private void jComboBoxElegirCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxElegirCuentaActionPerformed

    }

    private void jComboBoxEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstatusActionPerformed

    }

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        cheque.setMaeCuenta(Long.parseLong(jComboBoxElegirCuenta.getSelectedItem().toString()));
        cheque.setNumero(Integer.parseInt(textFieldNumero.getText()));
        cheque.setConcepto(textFieldConcepto.getText());
        cheque.setMaeProveedor(Long.parseLong(textFieldProveedor.getText()));
        cheque.setImporte(new java.math.BigDecimal(textFieldImporte.getText()));
        cheque.setTrsRegistroTransaccion(1);
        cheque.setMaeEstatus(jComboBoxEstatus.getSelectedIndex() + 1);
        dbManager.insertarCheque(cheque);
        JOptionPane.showMessageDialog(this, "Cheque generado correctamente");
    }

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarCheque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel background;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JComboBox<String> jComboBoxElegirCuenta;
    private javax.swing.JComboBox<String> jComboBoxEstatus;
    private javax.swing.JComboBox<String> jComboBoxTipoOperacion;
    private javax.swing.JLabel jLabelConcepto;
    private javax.swing.JLabel jLabelCuentaBancaria;
    private javax.swing.JLabel jLabelEstatus;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelImporte;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelProveedor;
    private javax.swing.JLabel jLabelTipoOperacion;
    private javax.swing.JTextField textFieldConcepto;
    private javax.swing.JTextField textFieldFecha;
    private javax.swing.JTextField textFieldImporte;
    private javax.swing.JTextField textFieldNumero;
    private javax.swing.JTextField textFieldProveedor;
    // End of variables declaration//GEN-END:variables
}
