/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author Edgardo Rivero
 */
public class IngresarDatosCliente extends javax.swing.JFrame {

    /**
     * Creates new form IngresarUsuario
     */
    public IngresarDatosCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre1 = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelApellidos = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        textFieldApellidos = new javax.swing.JTextField();
        textFieldCorreo = new javax.swing.JTextField();
        textFieldDireccion = new javax.swing.JTextField();
        textFieldTelefono = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        labelCorreo1 = new javax.swing.JLabel();
        labelNumeroDocumento = new javax.swing.JLabel();
        textFieldTelefono1 = new javax.swing.JTextField();
        labelNumeroDocumento1 = new javax.swing.JLabel();
        jComboBoxTipoDocumento = new javax.swing.JComboBox<>();

        labelNombre1.setBackground(new java.awt.Color(153, 153, 255));
        labelNombre1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre1.setText("Nombre:");
        labelNombre1.setToolTipText("");
        labelNombre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelNombre1.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setToolTipText("");
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombre.setBackground(new java.awt.Color(102, 153, 0));
        labelNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre.setText("Nombres");
        labelNombre.setToolTipText("");
        labelNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelNombre.setOpaque(true);
        background.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 86, 27));

        labelDireccion.setBackground(new java.awt.Color(102, 153, 0));
        labelDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDireccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDireccion.setText("Dirección");
        labelDireccion.setToolTipText("");
        labelDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelDireccion.setOpaque(true);
        background.add(labelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 86, 27));

        labelTelefono.setBackground(new java.awt.Color(102, 153, 0));
        labelTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTelefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTelefono.setText("Telefono");
        labelTelefono.setToolTipText("");
        labelTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelTelefono.setOpaque(true);
        background.add(labelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 317, 86, 27));

        labelCorreo.setBackground(new java.awt.Color(102, 153, 0));
        labelCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCorreo.setText("Correo");
        labelCorreo.setToolTipText("");
        labelCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelCorreo.setOpaque(true);
        background.add(labelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 357, 86, 27));

        labelApellidos.setBackground(new java.awt.Color(102, 153, 0));
        labelApellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelApellidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelApellidos.setText("Apellidos");
        labelApellidos.setToolTipText("");
        labelApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelApellidos.setOpaque(true);
        background.add(labelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 86, 27));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 126));

        textFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNombreActionPerformed(evt);
            }
        });
        background.add(textFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 121, 209, 27));

        textFieldApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldApellidosActionPerformed(evt);
            }
        });
        background.add(textFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 161, 209, 27));

        textFieldCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCorreoActionPerformed(evt);
            }
        });
        background.add(textFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 358, 209, 27));

        textFieldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDireccionActionPerformed(evt);
            }
        });
        background.add(textFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 200, 209, 27));

        textFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTelefonoActionPerformed(evt);
            }
        });
        background.add(textFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 318, 209, 27));

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        background.add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 434, -1, 27));

        labelCorreo1.setBackground(new java.awt.Color(204, 204, 204));
        labelCorreo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelCorreo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCorreo1.setText("Ingresar datos del nuevo cliente");
        labelCorreo1.setToolTipText("");
        labelCorreo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelCorreo1.setOpaque(true);
        background.add(labelCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 37, 410, 53));

        labelNumeroDocumento.setBackground(new java.awt.Color(102, 153, 0));
        labelNumeroDocumento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNumeroDocumento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumeroDocumento.setText("Documento");
        labelNumeroDocumento.setToolTipText("");
        labelNumeroDocumento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelNumeroDocumento.setOpaque(true);
        background.add(labelNumeroDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 239, 86, 27));

        textFieldTelefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTelefono1ActionPerformed(evt);
            }
        });
        background.add(textFieldTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 239, 209, 27));

        labelNumeroDocumento1.setBackground(new java.awt.Color(102, 153, 0));
        labelNumeroDocumento1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNumeroDocumento1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumeroDocumento1.setText("Tipo");
        labelNumeroDocumento1.setToolTipText("");
        labelNumeroDocumento1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelNumeroDocumento1.setOpaque(true);
        background.add(labelNumeroDocumento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 278, 86, 27));

        jComboBoxTipoDocumento.setEditable(true);
        jComboBoxTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Carnet de Extranjeria" }));
        jComboBoxTipoDocumento.setToolTipText("");
        jComboBoxTipoDocumento.setAutoscrolls(true);
        jComboBoxTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoDocumentoActionPerformed(evt);
            }
        });
        background.add(jComboBoxTipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 278, 209, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        String nombre = textFieldNombreActionPerformed(evt);
        String apellidos = textFieldApellidosActionPerformed(evt);
        String correo = textFieldCorreoActionPerformed(evt);
        String direccion = textFieldDireccionActionPerformed(evt);
        Long telefono = textFieldTelefonoActionPerformed(evt);

        db.nuevoCliente(nombre, apellidos, direccion, correo, direccion, telefono);

        
    }//GEN-LAST:event_botonAceptarActionPerformed

    private String textFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNombreActionPerformed
        return textFieldNombre.getText();
    }//GEN-LAST:event_textFieldNombreActionPerformed

    private String textFieldApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldApellidosActionPerformed
        return textFieldApellidos.getText();
    }//GEN-LAST:event_textFieldApellidosActionPerformed

    private String textFieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCorreoActionPerformed
        return textFieldCorreo.getText();
    }//GEN-LAST:event_textFieldCorreoActionPerformed

    private String textFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDireccionActionPerformed
        return textFieldDireccion.getText();
    }//GEN-LAST:event_textFieldDireccionActionPerformed

    private Long textFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTelefonoActionPerformed
        return Long.parseLong(textFieldTelefono.getText());
    }//GEN-LAST:event_textFieldTelefonoActionPerformed

    private void textFieldTelefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTelefono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTelefono1ActionPerformed

    private void jComboBoxTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoDocumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JComboBox<String> jComboBoxTipoDocumento;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelCorreo1;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelNumeroDocumento;
    private javax.swing.JLabel labelNumeroDocumento1;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField textFieldApellidos;
    private javax.swing.JTextField textFieldCorreo;
    private javax.swing.JTextField textFieldDireccion;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldTelefono;
    private javax.swing.JTextField textFieldTelefono1;
    // End of variables declaration//GEN-END:variables
}
