/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import db.dbInicioSesion;
import javax.swing.JOptionPane;

/**
 *
 * @author Edgardo Rivero
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form IngresarUsuario
     */
    public InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre1 = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelContraseña = new javax.swing.JLabel();
        textFieldContraseña = new javax.swing.JTextField();
        textFieldUsuario = new javax.swing.JTextField();
        botonIniciarSesion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelOlvidoContraseña = new javax.swing.JLabel();

        labelNombre1.setBackground(new java.awt.Color(153, 153, 255));
        labelNombre1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre1.setText("Nombre:");
        labelNombre1.setToolTipText("");
        labelNombre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelNombre1.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setToolTipText("");
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(204, 204, 204));
        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Inicio de Sesión");
        Titulo.setToolTipText("");
        Titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Titulo.setOpaque(true);
        background.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 340, 53));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1616080552275 (1).jpg"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 90));

        labelUsuario.setBackground(new java.awt.Color(0, 51, 255));
        labelUsuario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsuario.setText("Usuario");
        labelUsuario.setToolTipText("");
        labelUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelUsuario.setOpaque(true);
        background.add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 86, 27));

        labelContraseña.setBackground(new java.awt.Color(0, 51, 255));
        labelContraseña.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        labelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        labelContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelContraseña.setText("Contraseña");
        labelContraseña.setToolTipText("");
        labelContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelContraseña.setOpaque(true);
        background.add(labelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 86, 27));

        textFieldContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldContraseñaActionPerformed(evt);
            }
        });
        background.add(textFieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 190, 27));

        textFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldUsuarioActionPerformed(evt);
            }
        });
        background.add(textFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 190, 27));

        botonIniciarSesion.setText("Iniciar Sesion");
        botonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesionActionPerformed(evt);
            }
        });
        background.add(botonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, 27));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 500));

        jLabelOlvidoContraseña.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabelOlvidoContraseña.setText("¿Olvido su contraseña? Contacte con el encargado de informatica");
        background.add(jLabelOlvidoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 290, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldContraseñaActionPerformed
        try {
            String contraseña = textFieldContraseña.getText();
            if (contraseña.length() > 15) {
            throw new IllegalArgumentException("La contraseña no puede tener más de 15 caracteres");
            }
            // Code to handle valid input
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    //GEN-LAST:event_textFieldContraseñaActionPerformed

    private void textFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldUsuarioActionPerformed
        try {
            int usuario = Integer.parseInt(textFieldUsuario.getText());
            if (usuario < 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un valor entero válido para el usuario");
        }
    }//GEN-LAST:event_textFieldUsuarioActionPerformed

    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed
        String usuario = textFieldUsuario.getText();
        int usuarioint = Integer.parseInt(usuario);
        String contrasena = textFieldContraseña.getText();
        dbInicioSesion dbInicioSesion = new dbInicioSesion();
        if (dbInicioSesion.validarDatos(usuarioint, contrasena)) {
            JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso");
            Menu menuPrincipal = new Menu();
            menuPrincipal.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Inicio de sesión fallido");
        }
    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel background;
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JLabel jLabelOlvidoContraseña;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField textFieldContraseña;
    private javax.swing.JTextField textFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
